collections:
  - name: community.general
    version: 4.8.5
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.4.2
    source: https://galaxy.ansible.com

  - name: community.digitalocean 
    version: 1.0.0
    source: https://galaxy.ansible.com

  - name: awx.awx
    version: 24.0.0
    source: https://galaxy.ansible.com
